#!/usr/bin/env bash
# Configures an Ubuntu server
if [ "$(id -u)" -ne 0 ]; then
	echo "./0-change_your_home_IP: Permission denied"
	exit 1
fi
sed -i 's/127.0.0.1/127.0.0.2/' /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
