#!/usr/bin/env bash
# Server IP or hostname
server="100.26.50.133"

# Path to the private key
private_key="~/.ssh/school"

# SSH connection using single-character flags
ssh -i "$private_key" ubuntu@"$server"
